apiVersion: s3.aws.upbound.io/v1beta1
kind: Bucket
metadata: 
  name: akings-crossplane-bucket
  labels:
    testing.upbound.io/example-name: s3
spec:
  forProvider:
    region: eu-central-1
    tags:
      foo: test
  providerConfigRef:
    name: default
---
apiVersion: s3.aws.upbound.io/v1beta1
kind: BucketOwnershipControls
metadata:
  name: akings-crossplane-ownership
spec:
  forProvider:
    region: eu-central-1
    bucketSelector:
      matchLabels:
        testing.upbound.io/example-name: s3
    rule:
      - objectOwnership: BucketOwnerPreferred
  providerConfigRef:
    name: default

